refactor pages to support typescript
karlxavier/bookshelf-client pull request #1
Opened 2022-09-05 12:34 UTC by karlxavier

2022-09-05 14:49 UTC, normancapule reviewed
Does this compile properly in your local? Happy to approve if it does

2022-09-08 10:37 UTC, normancapule requested changes
Not yet there. Let's make it better 💪 

Also can you pls add proper descriptions in this PR? Since this is a FE PR, screenshots and gifs would help us review it better

2022-09-08 10:37 UTC, normancapule commented on pages/api/auth/[...nextauth].ts
> +      async authorize(credentials: any) {
Do not use `any`. What is the expected object structure of credentials?

2022-09-08 10:37 UTC, normancapule commented on pages/api/register.ts
> +      const hash = await bcrypt.hash(password, 0);
Why are you encrypting the password here? Shouldn't this be encrypted in the backend side instead?

2022-09-08 10:37 UTC, normancapule commented on pages/api/register.ts
> +    }
Do not add `api` functions inside components. These are not the responsibility of the components to know. Instead - these should be called from the api folder. 

api/register.ts
```

export const register = (payload: <type this to the expected payload structure>) => {
fetch(process.env.API_URI + '/v1/user_registration', {
        method: 'POST',
        body: JSON.stringify(payload),
        headers: {
          'Content-Type': 'application/json',
          'Accept-Language': 'en-US',
        },
      });
}
```

2022-09-08 10:37 UTC, normancapule commented on pages/api/register.ts
> +const bcrypt = require('bcrypt');
the `api` folder should be outside the `pages` folder. Next.js treats components inside `pages` differently

2022-09-08 10:37 UTC, normancapule commented on pages/components/layout.tsx
> +export default function Layout({ children }: any) {
please make use of rocket annotation for your components and functions. 

```suggestion
export const Layout = ({ children }: any) => {
```

2022-09-08 10:37 UTC, normancapule commented on pages/components/layout.tsx
> +export default function Layout({ children }: any) {
Please add an interface to properly type your props. 

since Layout is a regular component that receives children, it can be:

```
const Layout: React.FC = ({ children }) => {
}
```

or you can explicitly type it
```
interface LayoutProps extends React.FC { }

const Layout = ({ children }: LayoutProps) => {
```

2022-09-08 10:37 UTC, normancapule commented on pages/_app.js
>  import { SessionProvider } from 'next-auth/react';
Nice work using next-auth. How is it?

2022-09-08 10:37 UTC, normancapule commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "pages/_app.tsx", pages/index.js, "pages/discover.jsx", "pages/book/[id].js", "papages/middleware.tsx "pages/api/auth/[...nextauth2].ts",, "pages
This looks like a mess. Can you clean this up? There are some deleted files included in this array

2022-09-08 10:37 UTC, normancapule commented on pages/api/register.ts
> +    }
I don't understand what this means. What does `res.status(503)` do?

2022-09-08 10:37 UTC, normancapule commented on pages/components/wrapper.tsx
> +export default function Wrapper(props: any)
Since this is for authenticated pages, can you:
- rename this to AuthenticatedWrapper or AuthenticatedLayout
- maybe redirect the user to the login page instead of showing a `you are not authenticated` message

2022-09-08 10:37 UTC, normancapule commented on pages/components/wrapper.tsx
> +            href='/login'
Make use of [next/link](https://nextjs.org/docs/api-reference/next/link) instead of hard-coding the link in an anchor

2022-09-08 10:37 UTC, normancapule commented on pages/discover.tsx
> +      'Content-Type': 'application/x-www-form-urlencoded'
Connected to my comment about moving api functions into its own folders, please dry this up.

Bdw `btoa` is deprecated 
![image](https://user-images.githubusercontent.com/780659/189100404-79532132-7383-493f-8dab-1b5f6b6c91ae.png)

Also - want to verify - how does `+btoa('username:password')` work? Does this automatically fetch the JWT from next/auth?

2022-09-08 10:37 UTC, normancapule commented on pages/discover.tsx
> +                onClick={(e) => handleAddToList(e, book.id)}
Can you disable this button while `handleAddToList` is ongoing? Don't forget your loading states

2022-09-08 10:37 UTC, normancapule commented on pages/login.tsx
> +          setLoginError(result.error);
The `error` is not typed. What is the kind of error we can expect here?

2022-09-08 10:37 UTC, normancapule commented on pages/login.tsx
> +      if (result.error !== null)
FYI there is `response.ok` - you can use this to easily tell if it was ssuccessful https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

2022-09-08 10:41 UTC, normancapule commented on tsconfig.json
>      "jsx": "preserve",
bdw you can add `baseUrl: '.'` so that you can do non-absolute imports

from
`import { } from "../../components/Bla"`
to
`import { } from "components/Bla"`

2022-09-16 17:02 UTC, normancapule reviewed
I still see some issues with this PR. But let's aim at merging this huge PR and fix the comments incrementally in future PRs

2022-09-16 17:02 UTC, normancapule commented on components/Books/Book/props.ts
> +export interface BookProps {
You don't need to put this in another file. Especially if this is just the props of the component, and is not shared.

2022-09-16 17:02 UTC, normancapule commented on pages/Discover/index.tsx
> +  }
Make use of anonymous functions, instead of writing it with the `function` term. 

```
addToReadingBooks = (bookId: number) => 
```

2022-09-16 17:02 UTC, normancapule commented on pages/Discover/index.tsx
> +          <Books books={books} handleClick={addToReadingBooks.bind(this)} />
`function.bind(this)` was the practice before React has hooks, and before anonymous functions were widely used vs. class components. 

I'd recommend this approach instead:

```
handleClick=(addToReadingBooks)
```

2022-09-16 17:02 UTC, normancapule commented on components/Books/Book/props.ts
> +  handleClick: (bookId: null | any) => void;
please do not use `any`. Type this out. 

```
(bookId: number) => void
```

If you need assistance here - just let us know and we can book a pairing session

2022-09-16 17:02 UTC, normancapule commented on components/Books/props.ts
> +  };
This looks like a type that comes from the API. This should live in `api/types.ts` as `type Books`

2022-09-16 17:02 UTC, normancapule commented on components/Books/Book/index.tsx
> +    setLoading(false);
the `loading state` must come from the API function. Only the API function creating the request will know `for certain` if the request is finished, has failed, or is completed.

Even if the API request is still ongoing, the `loading` state here will become `false`.

2022-09-16 17:02 UTC, normancapule commented on pages/Discover/index.tsx
> +  const [books, setBooks] = useState<any>([]);
I'm still seeing `any` everywhere.

2022-09-16 17:02 UTC, normancapule commented on pages/Discover/index.tsx
> +  const [books, setBooks] = useState<any>([]);
FYI that your next project will not build because we are using `strict` typescript mode. Next build will report typescript errors.

2022-09-16 17:02 UTC, normancapule commented on pages/api/auth/[...nextauth].ts
> +      async authorize(credentials: any) {
You resolved this conversation but I still see `any` in here

2022-09-16 17:02 UTC, normancapule commented on components/Books/Book/index.tsx
> +    setLoading(false);
What I suggest:

Create a new function that is called when the request is completed.

```
const onComplete = (response: Book) => {
  setLoading(false);
  setHide(true);
}
```

Then pas this to the api function.

```
props.handleClick(bookId, onComplete)
```

Your api should know what to do if an `onComplete` function was passed as a parameter

```
export const AddToReadingList = async (bookId: number, onComplete?: (response: book) => void, onError: (error: ) => void) => {
      const payload = {
    id: bookId
  }
  const url = `${API_ENDPOINT}/v1/books/add_reading_list`

  const response = await fetchApi(
    url,
    'POST',
    {
      variables: JSON.stringify(payload),
    }
  )
  onComplete && onComplete(response)
  return response
} 
```

2022-09-16 17:02 UTC, normancapule commented on pages/register.ts
> +export default async (req: any, res: any) => {
What's this page?

2022-09-16 17:02 UTC, normancapule commented on pages/register.tsx
> +export default function Register() {
```suggestion
export default const Register = () => {
}
```

2022-09-21 02:31 UTC, karlxavier commented
@normancapule i already updated this PR and can we merge this for now? i will create a separate PR on other change requests which was not yet resolve. and yes better to have a pairing session on typescript 😄

2022-09-21 02:35 UTC, normancapule commented
@karlxavier go ahead and merge

2022-09-21 02:35 UTC, normancapule approved these changes
Let's merge this Big Chungus

2022-09-21 02:42 UTC, merged